cell_cfg:
  band: 78
  channel_bandwidth_MHz: 20
  common_scs: 30
  dl_arfcn: 632628
  nof_antennas_dl: 4
  nof_antennas_ul: 4
  pci: 1
  plmn: '00101'
  scheduler:
    nof_preselected_newtx_ues: 10
    policy:
      qos_sched:
        pf_fairness_coeff: 1.0
  tac: 7
cells:
- channel_bandwidth_MHz: 20
  pci: 10
cu_cp:
  amf:
    addr: 127.0.0.1
    bind_addr: 127.0.0.1
    port: 38412
    supported_tracking_areas:
    - plmn_list:
      - plmn: '00101'
        tai_slice_support_list:
        - sst: 1
      tac: 7
e2:
  addr: 127.0.0.1
  bind_addr: 127.0.0.1
  e2sm_kpm_enabled: true
  e2sm_rc_enabled: true
  enable_du_e2: true
  port: 36421
log:
  all_level: debug
pcap:
  mac_enable: false
  mac_filename: /tmp/gnb_mac.pcap
  ngap_enable: false
  ngap_filename: /tmp/gnb_ngap.pcap
