pipeline {

    agent any

    options {
        timestamps()
    }

    stages {

        stage('Configure') {
            steps {
                sh './ci/scripts/configure.sh'
            }
        }

        stage('Build') {
            steps {
                sh './ci/scripts/build.sh'
            }
        }

        stage('Scheduler Policy Unit Tests') {
            steps {
                sh './ci/scripts/test.sh'
            }
        }
    
    
       stage('Scheduler Integration Tests') {
           steps {
                 sh './ci/scripts/test_scheduler.sh'
            }
       }
      }

    post {

        success {
            echo 'Build completed successfully.'
        }

        failure {
            echo 'Build failed.'
        }

        always {
             archiveArtifacts artifacts: '**/*.log', fingerprint: true, allowEmptyArchive: true
        }
    }
}
